In [3]:
import math

In [6]:
import numpy as np

In [8]:
import array as arr

In [10]:
l = [1,2,"jack", "jill", 8.9]
type(l)

list

In [15]:
a = np.array(l)

['1' '2' 'jack' 'jill' '8.9']


In [14]:
type(a)

numpy.ndarray

In [16]:
np.array([[1,4],[4,5],[8,9],['j','k']])

array([['1', '4'],
       ['4', '5'],
       ['8', '9'],
       ['j', 'k']], dtype='<U11')

In [17]:
np.array([1,2,3], ndmin = 2)

array([[1, 2, 3]])

In [18]:
type(np.array([1,2,3], ndmin = 3))

numpy.ndarray

In [19]:
np.array([1,2,3], ndmin = 3)

array([[[1, 2, 3]]])

In [20]:
np.array([1,2,3], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [22]:
np.array([1,2,3], dtype = int)

array([1, 2, 3])

In [23]:
np.array([1,2,3], dtype = str)

array(['1', '2', '3'], dtype='<U1')

In [24]:
l = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [25]:
l

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
l[0][1] = 400

In [28]:
l

array([[  1, 400,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [29]:
l[1][2]

6

In [30]:
l = [1,2,3,4,5,6,7,8,9]

In [31]:
np.array(l)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.asarray(l)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.asanyarray(l)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
# All the three (np.array, np.asarray and np.asanyarray) are same!

In [39]:
np.fromfunction(lambda i,j : i==j, (5,5))

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [41]:
np.fromfunction(lambda i , j : i*j, (5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  2.,  4.,  6.,  8.],
       [ 0.,  3.,  6.,  9., 12.],
       [ 0.,  4.,  8., 12., 16.]])

In [42]:
[i*i for i in range(0,5)]

[0, 1, 4, 9, 16]

In [46]:
for i in range(0,5):
    print(i**2)

0
1
4
9
16


In [48]:
import numpy as np
np.fromstring("1 2 3 4 5 6 7 8 9", sep = " ", dtype = int)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [52]:
np.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [53]:
np.linspace(3,8)

array([3.        , 3.10204082, 3.20408163, 3.30612245, 3.40816327,
       3.51020408, 3.6122449 , 3.71428571, 3.81632653, 3.91836735,
       4.02040816, 4.12244898, 4.2244898 , 4.32653061, 4.42857143,
       4.53061224, 4.63265306, 4.73469388, 4.83673469, 4.93877551,
       5.04081633, 5.14285714, 5.24489796, 5.34693878, 5.44897959,
       5.55102041, 5.65306122, 5.75510204, 5.85714286, 5.95918367,
       6.06122449, 6.16326531, 6.26530612, 6.36734694, 6.46938776,
       6.57142857, 6.67346939, 6.7755102 , 6.87755102, 6.97959184,
       7.08163265, 7.18367347, 7.28571429, 7.3877551 , 7.48979592,
       7.59183673, 7.69387755, 7.79591837, 7.89795918, 8.        ])

In [54]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [55]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [56]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [62]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [64]:
np.zeros((3,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [65]:
np.zeros((2,3,3))+5

array([[[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]]])

In [66]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [68]:
np.linspace(2,4,3,axis = 0)

array([2., 3., 4.])

In [69]:
# --------------------------------------------------------------------------------------------------------------------------#

In [3]:
## First step is to import both the libraries

import pandas as pd
import numpy as np

In [4]:
df1 = (np.arange(0,100).reshape(10,10))
df1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [5]:
df = pd.DataFrame(df1)
df

0   1   2   3   4   5   6   7   8   9
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49
5  50  51  52  53  54  55  56  57  58  59
6  60  61  62  63  64  65  66  67  68  69
7  70  71  72  73  74  75  76  77  78  79
8  80  81  82  83  84  85  86  87  88  89
9  90  91  92  93  94  95  96  97  98  99

In [6]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [7]:
## Playing with the data frame

df = pd.DataFrame(df1,index=["Row 1", "Row 2","Row3","Row 4","Row 5", "Row 6", "Row 7", "Row 8", "Row 9", "Row 10"], columns = ["Col 1", "Col 2", "Col 3", "Col 4", "Col 5", "Col 6", "Col 7", "Col 8", "Col 9", "Col 10"])

In [8]:
df

Col 1  Col 2  Col 3  Col 4  Col 5  Col 6  Col 7  Col 8  Col 9  Col 10
Row 1       0      1      2      3      4      5      6      7      8       9
Row 2      10     11     12     13     14     15     16     17     18      19
Row3       20     21     22     23     24     25     26     27     28      29
Row 4      30     31     32     33     34     35     36     37     38      39
Row 5      40     41     42     43     44     45     46     47     48      49
Row 6      50     51     52     53     54     55     56     57     58      59
Row 7      60     61     62     63     64     65     66     67     68      69
Row 8      70     71     72     73     74     75     76     77     78      79
Row 9      80     81     82     83     84     85     86     87     88      89
Row 10     90     91     92     93     94     95     96     97     98      99

In [9]:
df.head()

Col 1  Col 2  Col 3  Col 4  Col 5  Col 6  Col 7  Col 8  Col 9  Col 10
Row 1      0      1      2      3      4      5      6      7      8       9
Row 2     10     11     12     13     14     15     16     17     18      19
Row3      20     21     22     23     24     25     26     27     28      29
Row 4     30     31     32     33     34     35     36     37     38      39
Row 5     40     41     42     43     44     45     46     47     48      49

In [10]:
df.head(1)

Col 1  Col 2  Col 3  Col 4  Col 5  Col 6  Col 7  Col 8  Col 9  Col 10
Row 1      0      1      2      3      4      5      6      7      8       9

In [11]:
df.tail()

Col 1  Col 2  Col 3  Col 4  Col 5  Col 6  Col 7  Col 8  Col 9  Col 10
Row 6      50     51     52     53     54     55     56     57     58      59
Row 7      60     61     62     63     64     65     66     67     68      69
Row 8      70     71     72     73     74     75     76     77     78      79
Row 9      80     81     82     83     84     85     86     87     88      89
Row 10     90     91     92     93     94     95     96     97     98      99

In [12]:
df.tail(3)

Col 1  Col 2  Col 3  Col 4  Col 5  Col 6  Col 7  Col 8  Col 9  Col 10
Row 8      70     71     72     73     74     75     76     77     78      79
Row 9      80     81     82     83     84     85     86     87     88      89
Row 10     90     91     92     93     94     95     96     97     98      99

In [14]:
df.shape

(10, 10)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, Row 1 to Row 10
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Col 1   10 non-null     int32
 1   Col 2   10 non-null     int32
 2   Col 3   10 non-null     int32
 3   Col 4   10 non-null     int32
 4   Col 5   10 non-null     int32
 5   Col 6   10 non-null     int32
 6   Col 7   10 non-null     int32
 7   Col 8   10 non-null     int32
 8   Col 9   10 non-null     int32
 9   Col 10  10 non-null     int32
dtypes: int32(10)
memory usage: 480.0+ bytes


In [20]:
df.dtypes

Col 1     int32
Col 2     int32
Col 3     int32
Col 4     int32
Col 5     int32
Col 6     int32
Col 7     int32
Col 8     int32
Col 9     int32
Col 10    int32
dtype: object

In [21]:
df['Col 1']

Row 1      0
Row 2     10
Row3      20
Row 4     30
Row 5     40
Row 6     50
Row 7     60
Row 8     70
Row 9     80
Row 10    90
Name: Col 1, dtype: int32

In [24]:
## Accessing the elements using loc and iloc

df.loc["Row 1"]

Col 1     0
Col 2     1
Col 3     2
Col 4     3
Col 5     4
Col 6     5
Col 7     6
Col 8     7
Col 9     8
Col 10    9
Name: Row 1, dtype: int32

In [25]:
type(df.loc["Row 1"])

pandas.core.series.Series

In [36]:
#df.iloc[From this row : To this row, From this column : To this column]

df.iloc[1:6,1:8]

Col 2  Col 3  Col 4  Col 5  Col 6  Col 7  Col 8
Row 2     11     12     13     14     15     16     17
Row3      21     22     23     24     25     26     27
Row 4     31     32     33     34     35     36     37
Row 5     41     42     43     44     45     46     47
Row 6     51     52     53     54     55     56     57

In [34]:
df

Col 1  Col 2  Col 3  Col 4  Col 5  Col 6  Col 7  Col 8  Col 9  Col 10
Row 1       0      1      2      3      4      5      6      7      8       9
Row 2      10     11     12     13     14     15     16     17     18      19
Row3       20     21     22     23     24     25     26     27     28      29
Row 4      30     31     32     33     34     35     36     37     38      39
Row 5      40     41     42     43     44     45     46     47     48      49
Row 6      50     51     52     53     54     55     56     57     58      59
Row 7      60     61     62     63     64     65     66     67     68      69
Row 8      70     71     72     73     74     75     76     77     78      79
Row 9      80     81     82     83     84     85     86     87     88      89
Row 10     90     91     92     93     94     95     96     97     98      99

In [35]:
df.iloc[1:3,5:9]

Col 6  Col 7  Col 8  Col 9
Row 2     15     16     17     18
Row3      25     26     27     28

In [37]:
df.iloc[:,1:].values

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19],
       [21, 22, 23, 24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36, 37, 38, 39],
       [41, 42, 43, 44, 45, 46, 47, 48, 49],
       [51, 52, 53, 54, 55, 56, 57, 58, 59],
       [61, 62, 63, 64, 65, 66, 67, 68, 69],
       [71, 72, 73, 74, 75, 76, 77, 78, 79],
       [81, 82, 83, 84, 85, 86, 87, 88, 89],
       [91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [38]:
type(df.iloc[:,1:].values)

numpy.ndarray

In [43]:
df['Col 1'].value_counts()

0     1
10    1
20    1
30    1
40    1
50    1
60    1
70    1
80    1
90    1
Name: Col 1, dtype: int64

In [45]:
df.isnull()

Col 1  Col 2  Col 3  Col 4  Col 5  Col 6  Col 7  Col 8  Col 9  Col 10
Row 1   False  False  False  False  False  False  False  False  False   False
Row 2   False  False  False  False  False  False  False  False  False   False
Row3    False  False  False  False  False  False  False  False  False   False
Row 4   False  False  False  False  False  False  False  False  False   False
Row 5   False  False  False  False  False  False  False  False  False   False
Row 6   False  False  False  False  False  False  False  False  False   False
Row 7   False  False  False  False  False  False  False  False  False   False
Row 8   False  False  False  False  False  False  False  False  False   False
Row 9   False  False  False  False  False  False  False  False  False   False
Row 10  False  False  False  False  False  False  False  False  False   False

In [50]:
df.isnull().sum()

Col 1     0
Col 2     0
Col 3     0
Col 4     0
Col 5     0
Col 6     0
Col 7     0
Col 8     0
Col 9     0
Col 10    0
dtype: int64

In [49]:
df.duplicated().sum()

0

In [53]:
df.drop('Col 10', axis=1, inplace = True)

In [55]:
df

Col 1  Col 2  Col 3  Col 4  Col 5  Col 6  Col 7  Col 8  Col 9
Row 1       0      1      2      3      4      5      6      7      8
Row 2      10     11     12     13     14     15     16     17     18
Row3       20     21     22     23     24     25     26     27     28
Row 4      30     31     32     33     34     35     36     37     38
Row 5      40     41     42     43     44     45     46     47     48
Row 6      50     51     52     53     54     55     56     57     58
Row 7      60     61     62     63     64     65     66     67     68
Row 8      70     71     72     73     74     75     76     77     78
Row 9      80     81     82     83     84     85     86     87     88
Row 10     90     91     92     93     94     95     96     97     98

In [56]:
df.describe()

Col 1      Col 2      Col 3      Col 4      Col 5      Col 6  \
count  10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   
mean   45.000000  46.000000  47.000000  48.000000  49.000000  50.000000   
std    30.276504  30.276504  30.276504  30.276504  30.276504  30.276504   
min     0.000000   1.000000   2.000000   3.000000   4.000000   5.000000   
25%    22.500000  23.500000  24.500000  25.500000  26.500000  27.500000   
50%    45.000000  46.000000  47.000000  48.000000  49.000000  50.000000   
75%    67.500000  68.500000  69.500000  70.500000  71.500000  72.500000   
max    90.000000  91.000000  92.000000  93.000000  94.000000  95.000000   

           Col 7      Col 8      Col 9  
count  10.000000  10.000000  10.000000  
mean   51.000000  52.000000  53.000000  
std    30.276504  30.276504  30.276504  
min     6.000000   7.000000   8.000000  
25%    28.500000  29.500000  30.500000  
50%    51.000000  52.000000  53.000000  
75%    73.500000  74.500000  75.500000  
max    96.000000  97.000000  98.000000

In [57]:
df.duplicated(keep='last')

Row 1     False
Row 2     False
Row3      False
Row 4     False
Row 5     False
Row 6     False
Row 7     False
Row 8     False
Row 9     False
Row 10    False
dtype: bool

In [58]:
df.duplicated(keep=False)

Row 1     False
Row 2     False
Row3      False
Row 4     False
Row 5     False
Row 6     False
Row 7     False
Row 8     False
Row 9     False
Row 10    False
dtype: bool

In [59]:
df.drop_duplicates()

Col 1  Col 2  Col 3  Col 4  Col 5  Col 6  Col 7  Col 8  Col 9
Row 1       0      1      2      3      4      5      6      7      8
Row 2      10     11     12     13     14     15     16     17     18
Row3       20     21     22     23     24     25     26     27     28
Row 4      30     31     32     33     34     35     36     37     38
Row 5      40     41     42     43     44     45     46     47     48
Row 6      50     51     52     53     54     55     56     57     58
Row 7      60     61     62     63     64     65     66     67     68
Row 8      70     71     72     73     74     75     76     77     78
Row 9      80     81     82     83     84     85     86     87     88
Row 10     90     91     92     93     94     95     96     97     98

In [61]:
df[df["Col 1"]>=50]

Col 1  Col 2  Col 3  Col 4  Col 5  Col 6  Col 7  Col 8  Col 9
Row 6      50     51     52     53     54     55     56     57     58
Row 7      60     61     62     63     64     65     66     67     68
Row 8      70     71     72     73     74     75     76     77     78
Row 9      80     81     82     83     84     85     86     87     88
Row 10     90     91     92     93     94     95     96     97     98

In [1]:
import numpy as np
import pandas as pd

In [3]:
lst_data = [[1,2,3],[3,4,np.nan],[5,6,np.nan],[np.nan, np.nan, np.nan]]
lst_data

[[1, 2, 3], [3, 4, nan], [5, 6, nan], [nan, nan, nan]]

In [4]:
df = pd.DataFrame(lst_data)
df

0    1    2
0  1.0  2.0  3.0
1  3.0  4.0  NaN
2  5.0  6.0  NaN
3  NaN  NaN  NaN

In [5]:
df.head(2)

0    1    2
0  1.0  2.0  3.0
1  3.0  4.0  NaN

In [6]:
df.tail(1)

0   1   2
3 NaN NaN NaN

In [7]:
df.isnull().sum()

0    1
1    1
2    3
dtype: int64

In [8]:
df.dropna(axis=1, inplace = True)
df

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [9]:
df = pd.DataFrame(np.random.randn(5,5), index = ["Row 1", "Row 2", "Row 3", "Row 4", "Row 5"], columns = ["Col 1", "Col 2", "Col 3", "Col 4", "Col 5" ])

In [10]:
df

Col 1     Col 2     Col 3     Col 4     Col 5
Row 1 -1.189719 -0.372796  1.524066 -0.672161  0.253873
Row 2  0.151485 -0.469900  1.118692 -0.254034 -0.333934
Row 3  1.663797 -1.180870  0.043058 -0.502161 -0.293565
Row 4  0.669052 -0.070208  0.032066  0.414576  0.245738
Row 5 -0.831694 -0.475225 -1.631165  0.456660 -0.380961

In [11]:
pd.isna(df['Col 2'])

Row 1    False
Row 2    False
Row 3    False
Row 4    False
Row 5    False
Name: Col 2, dtype: bool

In [14]:
df["Col 3"].notna()

Row 1    True
Row 2    True
Row 3    True
Row 4    True
Row 5    True
Name: Col 3, dtype: bool

In [15]:
from io import StringIO, BytesIO

In [16]:
data = ('Col 1, Col 2, Col 3\n'
       'x,y,1\n'
       'a,b,2\n'
       'c,d,3')

In [17]:
data

'Col 1, Col 2, Col 3\nx,y,1\na,b,2\nc,d,3'

In [18]:
type(data)

str

In [24]:
df = pd.read_csv(StringIO(data))
df

Col 1  Col 2   Col 3
0     x      y       1
1     a      b       2
2     c      d       3

In [25]:
 df.to_csv('Test.csv')

In [27]:
%ls

 Volume in drive C has no label.
 Volume Serial Number is 9C44-0518

 Directory of C:\Users\lenovo

01-02-2023  14:37    <DIR>          .
28-09-2022  21:17    <DIR>          ..
01-02-2023  14:38    <DIR>          .conda
20-12-2022  20:33                25 .condarc
20-12-2022  20:32    <DIR>          .continuum
30-01-2023  14:30    <DIR>          .ipynb_checkpoints
21-12-2022  14:09    <DIR>          .ipython
26-12-2022  14:53    <DIR>          .jupyter
28-05-2022  21:55             6,819 -1.14-windows.xml
31-01-2022  15:24    <DIR>          3D Objects
01-02-2023  14:37           101,614 Adv Python BIT (Numpy & Pandas).ipynb
30-01-2023  14:55            35,628 Assignments.ipynb
17-01-2023  14:49             2,909 BMI.log
17-01-2023  14:21                 0 BMICalculator.txt
29-09-2022  02:16    <DIR>          Contacts
10-05-2022  12:47    <DIR>          Documents
30-01-2023  14:55            21,985 Doubts.ipynb
31-01-2023  22:10    <DIR>          Downloads
29-09-2022  02:16    <DIR>    

In [3]:
import pandas as pd

In [57]:
Data = {"Car_name":"Creta" , "Colour": "White" , "Torque": "113 nm" , "Engine":"1500 cc" , "Mileage":"12 kmpl"}

In [58]:
Data

{'Car_name': 'Creta',
 'Colour': 'White',
 'Torque': '113 nm',
 'Engine': '1500 cc',
 'Mileage': '12 kmpl'}

In [62]:
pd.DataFrame(Data)

ValueError: If using all scalar values, you must pass an index

In [1]:
pip install html5lib

     ------------------------------------ 112.2/112.2 kB 935.2 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [4]:
url_mcc = 'https://en.wikipedia.org/wiki/Mobile_country_code'
dfs =  pd.read_html(url_mcc, match = "Country" , header = 0)
dfs[0]

Mobile country code                                    Country ISO 3166  \
0                    289                                 A Abkhazia    GE-AB   
1                    412                                Afghanistan       AF   
2                    276                                    Albania       AL   
3                    603                                    Algeria       DZ   
4                    544  American Samoa (United States of America)       AS   
..                   ...                                        ...      ...   
247                  452                                    Vietnam       VN   
248                  543                        W Wallis and Futuna       WF   
249                  421                                    Y Yemen       YE   
250                  645                                   Z Zambia       ZM   
251                  648                                   Zimbabwe       ZW   

                                  Mobile network codes National MNC authority  \
0             List of mobile network codes in Abkhazia                    NaN   
1          List of mobile network codes in Afghanistan                    NaN   
2              List of mobile network codes in Albania                    NaN   
3              List of mobile network codes in Algeria                    NaN   
4       List of mobile network codes in American Samoa                    NaN   
..                                                 ...                    ...   
247        List of mobile network codes in the Vietnam                    NaN   
248  List of mobile network codes in Wallis and Futuna                    NaN   
249          List of mobile network codes in the Yemen                    NaN   
250             List of mobile network codes in Zambia                    NaN   
251           List of mobile network codes in Zimbabwe                    NaN   

                      Remarks  
0    MCC is not listed by ITU  
1                         NaN  
2                         NaN  
3                         NaN  
4                         NaN  
..                        ...  
247                       NaN  
248                       NaN  
249                       NaN  
250                       NaN  
251                       NaN  

[252 rows x 6 columns]

In [8]:
df = pd.read_csv(r"C:\Users\lenovo\Downloads\train.csv")

In [9]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [11]:
df.head(6)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q

In [12]:
df.tail(6)

PassengerId  Survived  Pclass                                      Name  \
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket    Fare Cabin Embarked  
885  female  39.0      0      5      382652  29.125   NaN        Q  
886    male  27.0      0      0      211536  13.000   NaN        S  
887  female  19.0      0      0      112053  30.000   B42        S  
888  female   NaN      1      2  W./C. 6607  23.450   NaN        S  
889    male  26.0      0      0      111369  30.000  C148        C  
890    male  32.0      0      0      370376   7.750   NaN        Q

In [13]:
df.shape

(891, 12)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [15]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [16]:
df.isna()

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False   
1          False     False   False  False  False  False  False  False   False   
2          False     False   False  False  False  False  False  False   False   
3          False     False   False  False  False  False  False  False   False   
4          False     False   False  False  False  False  False  False   False   
..           ...       ...     ...    ...    ...    ...    ...    ...     ...   
886        False     False   False  False  False  False  False  False   False   
887        False     False   False  False  False  False  False  False   False   
888        False     False   False  False  False   True  False  False   False   
889        False     False   False  False  False  False  False  False   False   
890        False     False   False  False  False  False  False  False   False   

      Fare  Cabin  Embarked  
0    False   True     False  
1    False  False     False  
2    False   True     False  
3    False  False     False  
4    False   True     False  
..     ...    ...       ...  
886  False   True     False  
887  False  False     False  
888  False   True     False  
889  False  False     False  
890  False   True     False  

[891 rows x 12 columns]

In [17]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [18]:
df.drop_duplicates()

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [30]:
df['Pclass'].unique()

array([3, 1, 2], dtype=int64)

In [31]:
df['Sex'].unique()

array(['male', 'female'], dtype=object)

In [52]:
a = df['Age'].max()
b = df['Age'].min()

In [53]:
df['Name'][a]

'Waelens, Mr. Achille'

In [60]:
# Find the person with minimum age.
# Age less than 24.
# Person with the maximum fare.
# Number of people survived and not survived.
# Number of males and females.

df['Name']["Age"].min()

KeyError: 'Age'

In [9]:
import seaborn as sns
import numpy as np
import pandas as pd

In [10]:
df= sns.load_dataset('tips')

URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

In [11]:
df = pd.read_csv(r"C:\Users\lenovo\Downloads\tips.csv")

In [12]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [13]:
df.corr()

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000

In [16]:
df.corr(method = 'spearman')

total_bill       tip      size
total_bill    1.000000  0.678968  0.604791
tip           0.678968  1.000000  0.468268
size          0.604791  0.468268  1.000000

In [17]:
df.corr(method = 'pearson')

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000

In [18]:
df.cov()

total_bill       tip      size
total_bill   79.252939  8.323502  5.065983
tip           8.323502  1.914455  0.643906
size          5.065983  0.643906  0.904591

In [19]:
import scipy.stats as stats

In [21]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4